### Importing libraries

In [228]:
import pandas as pd
import numpy as num

### Loading Datasets

In [229]:
df_2019 = pd.read_csv("Divvy_Trips_2019_Q1.csv")
df_2020=pd.read_csv("Divvy_Trips_2020_Q1.csv")

### Checking Dataset Dimensions
The shape function is used to determine the number of rows and columns in the 2019 dataset.

In [230]:
print(df_2019.shape)

(365069, 12)

### Checking Dataset Dimensions
The shape function is used to determine the number of rows and columns in the 2020 dataset.

In [231]:
print(df_2020.shape)

(426887, 13)

### Viewing Column Names
The column names of the 2019  dataset are displayed for inspection.

In [232]:
print(df_2019.columns)

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

### Viewing Column Names
The column names of the 2020 dataset are displayed for inspection.

In [233]:
print(df_2020.columns)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

### Renaming Columns
The column names in the 2019 dataset are renamed to match the 2020 dataset structure for consistency.

In [234]:
df_2019=df_2019.rename(columns={ 'trip_id':'ride_id',
                                'bike_id':'ridable_type',
                               'start_time':'started_at',
                               'end_time':'ended_at',
                               'usertype':'member_casual'})

### Describe the data

In [235]:
df_2019.describe()

,ride_id,bikeid,from_station_id,to_station_id,birthyear
count,3.650690e+05,365069.000000,365069.000000,365069.000000,347046.000000
mean,2.196087e+07,3429.484607,198.088816,198.581123,1981.674297
std,1.271750e+05,1923.321025,153.493553,154.468304,11.245683
min,2.174244e+07,1.000000,2.000000,2.000000,1900.000000
25%,2.184876e+07,1777.000000,76.000000,76.000000,1975.000000
50%,2.196183e+07,3489.000000,170.000000,168.000000,1985.000000
75%,2.207182e+07,5157.000000,287.000000,287.000000,1990.000000
max,2.217853e+07,6471.000000,665.000000,665.000000,2003.000000

### Checking Missing Values
The dataset is checked for null or missing values in each column.

In [236]:
print(df_2020.isnull().sum())

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      1
end_station_id        1
start_lat             0
start_lng             0
end_lat               1
end_lng               1
member_casual         0
dtype: int64

### Merging Datasets
The 2019 and 2020 datasets are combined into a single dataset for analysis.

In [237]:
all_trips=pd.concat([df_2019,df_2020],ignore_index=True)

### Previewing the Dataset
The first five rows of the merged dataset are displayed for inspection.

In [238]:
all_trips.head(5)

,ride_id,started_at,ended_at,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,member_casual,...,birthyear,rideable_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,2167.0,390.0,199.0,Wabash Ave & Grand Ave,84.0,Milwaukee Ave & Grand Ave,Subscriber,...,1989.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,4386.0,441.0,44.0,State St & Randolph St,624.0,Dearborn St & Van Buren St (*),Subscriber,...,1990.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,1524.0,829.0,15.0,Racine Ave & 18th St,644.0,Western Ave & Fillmore St (*),Subscriber,...,1994.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,252.0,"1,783.0",123.0,California Ave & Milwaukee Ave,176.0,Clark St & Elm St,Subscriber,...,1993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,1170.0,364.0,173.0,Mies van der Rohe Way & Chicago Ave,35.0,Streeter Dr & Grand Ave,Subscriber,...,1994.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Calculating Ride Duration
A new column named ride_length is created by calculating the difference between trip end time and start time.

In [239]:
all_trips['ride_length']=pd.to_datetime(all_trips['ended_at'])-pd.to_datetime(all_trips['started_at'])

### Viewing Ride Length
The first few values of the ride_length column are displayed for verification.

In [240]:
print(all_trips['ride_length'].head())

0   0 days 00:06:30
1   0 days 00:07:21
2   0 days 00:13:49
3   0 days 00:29:43
4   0 days 00:06:04
Name: ride_length, dtype: timedelta64[ns]

### Day of Week Extraction
Converting 'started_at' to datetime and extracting 
the day of the week for ride pattern analysis.

In [241]:
all_trips['day_of_week']=pd.to_datetime(all_trips['started_at']).dt.dayofweek
print(all_trips['day_of_week'].head())

0    1
1    1
2    1
3    1
4    1
Name: day_of_week, dtype: int32

### Filtering Invalid Rides
Removing rides with zero or negative duration, 
keeping only trips lasting at least 1 minute.

In [242]:
all_trips=all_trips[all_trips['ride_length']>pd.Timedelta(0)]
all_trips=all_trips[all_trips['ride_length']>= pd.Timedelta(minutes=1)]
print(all_trips.isnull().sum())

ride_id                    0
started_at                 0
ended_at                   0
bikeid                419216
tripduration          419216
from_station_id       419216
from_station_name     419216
to_station_id         419216
to_station_name       419216
member_casual              0
gender                438927
birthyear             437239
rideable_type         365069
start_station_name    365069
start_station_id      365069
end_station_name      365069
end_station_id        365069
start_lat             365069
start_lng             365069
end_lat               365069
end_lng               365069
ride_length                0
day_of_week                0
dtype: int64

### Checking Duplicates
Verifying there are no duplicate rows in the dataset.

In [243]:
all_trips.duplicated().sum()

0

### Selecting Relevant Columns
Keeping only the 6 columns needed for analysis.

In [244]:
cols_to_keep=['ride_id','started_at','ended_at','member_casual','ride_length','day_of_week']
all_trips=all_trips[['ride_id','started_at','ended_at','member_casual','ride_length','day_of_week']]

### Final Dataset Shape
Confirming the cleaned dataset has 784,285 rows and 6 columns.

In [245]:
print("final shape:" ,all_trips.shape)

final shape: (784285, 6)

### Summary Statistics
Reviewing ride length distribution, most common 
day, and member type breakdown.

In [246]:
print(all_trips['ride_length'].describe())
print("mode:",all_trips['day_of_week'].mode()[0])
print(all_trips['member_casual'].value_counts())

count                       784285
mean     0 days 00:19:55.274378574
std      0 days 09:16:14.567965138
min                0 days 00:01:00
25%                0 days 00:05:33
50%                0 days 00:09:02
75%                0 days 00:15:15
max              123 days 01:20:22
Name: ride_length, dtype: object
mode: 1
member_casual
member        374687
Subscriber    341906
casual         44529
Customer       23163
Name: count, dtype: int64

### Converting Ride Length to Minutes
Converting ride length from timedelta to 
numeric minutes for easier analysis.

In [247]:
all_trips['ride_length_minutes']=all_trips['ride_length'].dt.total_seconds()/60

### Ride Patterns Analysis
Calculating average ride length by member type 
and total rides by day of week.

In [248]:
print("=== AVERAGE RIDE LENGTH BY MEMBER TYPE===")
print(all_trips.groupby('member_casual')['ride_length_minutes'].mean())
print("\n===RIDES BY DAY OFWEEK===")
print(all_trips['day_of_week'].value_counts().sort_index())

=== AVERAGE RIDE LENGTH BY MEMBER TYPE===
member_casual
Customer       61.941927
Subscriber     13.892870
casual        104.276067
member         12.799494
Name: ride_length_minutes, dtype: float64

===RIDES BY DAY OFWEEK===
day_of_week
0    115453
1    134680
2    128984
3    131725
4    122620
5     72521
6     78302
Name: count, dtype: int64

### Standardizing Member Types
Renaming 'Subscriber' to 'member' and 
'Customer' to 'casual' for consistency.

In [249]:
all_trips['member_casual']=all_trips['member_casual'].replace({
    'Subscriber':'member',
    'Customer':'casual'
})

print("member typesafter fix:")
print(all_trips['member_casual'].value_counts())

member typesafter fix:
member_casual
member    716593
casual     67692
Name: count, dtype: int64

### Adding Ride Count Column
Creating a count column with value 1 
for each ride record.

In [250]:
all_trips['count_ride_id]']=1

### Extracting Month
Converting 'started_at' to datetime and 
extracting the month for trend analysis.

In [251]:
all_trips['started_at'] = pd.to_datetime(all_trips['started_at'])
all_trips['month'] = all_trips['started_at'].dt.month
print(all_trips['month'].value_counts().sort_index())

month
1    245906
2    233867
3    304512
Name: count, dtype: int64

### Checking Shape
Verifying the final dimensions of the dataset.

In [252]:
print(all_trips.shape)

(784285, 9)

### Average Ride Length by Member Type

In [253]:
print(all_trips.groupby('member_casual')['ride_length_minutes'].mean())

member_casual
casual    89.790076
member    13.321173
Name: ride_length_minutes, dtype: float64

### Extracting Month Number
Pulling the month from 'started_at' 
for monthly trend analysis.

In [254]:
all_trips['month'] = all_trips['started_at'].dt.month

### Creating Summary Table
Grouping rides by month, day of week, 
and member type, then exporting to CSV.

In [255]:
summary = all_trips.groupby(
    ['month', 'day_of_week', 'member_casual']
)['ride_id'].count().reset_index()

summary.columns = ['month', 'day_of_week', 
                   'member_casual', 'count_ride_id']

summary.to_csv("final_cyclistic1_summary.csv", index=False)
print("Exported successfully!")
print(summary.shape)

Exported successfully!
(42, 4)

### final export
Saving the final summary table (42 rows, 
4 columns) to CSV for visualization.

In [256]:
summary.to_csv("final_cyclistic1_summary.csv", index=False)
print("Final correct export done!")
print(summary.shape)

Final correct export done!
(42, 4)